[package]
name = "dick-grower-bot"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Telegram Bot framework and localization library
teloxide = { version = "0.13.0", default-features = false, features = ["macros", "webhooks-axum", "rustls", "ctrlc_handler"] }
rust-i18n = "3.1.2"
# Asynchronous runtime, web server, metrics
tokio = { version =  "1.41.1", default-features = false, features = ["rt-multi-thread", "macros"] }
axum = "0.7.7"
axum-prometheus = "0.7.0"
prometheus = "0.13.4"
# Logging, tracing and envs
log = "0.4.22"
pretty_env_logger = "0.5.0"
dotenvy = "0.15.7"
tracing = "0.1.41"
tracing-core = "0.1.33"
tracing-subscriber = "0.3.19"
tracing-opentelemetry = "0.28.0"
tracing-loki = "0.2.5"
opentelemetry = "0.27.1"
# Database and SQL
sqlx = { version = "0.8.2", features = [ "runtime-tokio", "postgres", "chrono", "tls-rustls" ] }
# HTTP client with caching
reqwest = { version = "0.12.9", default-features = false, features = ["rustls-tls", "json"] }
# Serialization / deserialization
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
# HTML and templates
tinytemplate = "1.2.1"
# Derive macros
strum = "0.26.3"
strum_macros = "0.26.4"
derive_more = { version = "1.0.0", features = ["display", "from", "constructor", "error", "from_str"] }
anyhow = { version = "1.0.94", features = ["backtrace"] }
# Other basic stuff
regex = "1.11.1"
rand = "0.8.5"
chrono = { version = "0.4.39", features = [ "serde" ] }
base64 = "0.22.1"
byteorder = "1.5.0"
flurry = "0.5.2"
sha2 = "0.10.8"
# Rust specific stuff
once_cell = "1.20.2"
futures = "0.3.31"
async-trait = "0.1.83"
num-traits = "0.2.19"
downcast-rs = "1.2.1"

[dev-dependencies]
testcontainers = "0.23.1"
